config/routes.rb
require 'sidekiq/web'
Sndl::Application.routes.draw do
 

  resources :teams

  resources :meter_reader_statuses

  resources :meter_statuses

  resources :dtc_staffs,  :path => "clusters"

  resources :mobile_devises

  mount Sidekiq::Web, at: '/sidekiq'

  get "homes/index"

   root 'sessions#new'

   resources :users do
    collection { post :import }
    collection { get :search }
  end
 
  resources :sessions, :only => [:new,:create,:destroy,:edit]

  get 'dashboard' => 'users#dashboard', :as => 'user_root'

  get '/add_staff' =>'users#new'

  get '/signin' =>'sessions#new'

  get  '/users/:id/edit' => "users#edit" 

  post '/signout' =>'sessions#destroy'

  get '/readings/:id/toggled_status'  => "readings#toggled_status"

  get '/user/:id/dtc_staffs', :to => "users#dtc"

  get '/dtc_staff/:dtc', :to => "dtc_staffs#dtc"
 
  get '/consumer/:consno', :to => "consumers#consumer"

  post "/dtc_staffs/update_model", :to => "dtc_staffs#update_model" 

  get '/readings/submit', :to => "readings#submit"

  get '/mobileusers/:id/delete', :to => "mobileusers#destroy"

  get '/readings/consumer_status', :to => "readings#consumer_status"

   get '/readings/b30', :to => "readings#b30"

  get 'search'  => "teams#search"
 
  get 'search_vendor'  => "teams#search_vendor"
  
  get 'search_vendor_report'  => "readings#search_vendor_report"

  get 'search_vendor_summary'  => "readings#search_vendor_summary"
  
  get 'search_by_reader'  => "readings#search_by_reader"
  
  get  'search_by_date'  => "readings#search_by_date"

  get  'search_by_cluster'  => "readings#search_by_cluster"

  get  'search_by_date_summary'  => "readings#search_by_date_summary"

  get  'user_tracking'  => "readings#user_tracking"

  get  'user_tracking_report'  => "readings#user_tracking_report"

  get 'user_map' => 'readings#user_map'

 get 'search_all' => 'users#search_all'

  get 'readers_map' => 'readings#readers_map'
 
 resources :password_resets
 resources :staffs
 resources :readings do
  member do
    get 'show_image'
  end
  collection do
    get 'activity_report'
    get 'activity_summary_report'
  end
 end
resources :mobileusers

resources :consumers do
    collection do 
      get 'route_list'  => "consumers#route_list"
      get 'add_csv'
      get 'route'
      post 'import'
    end 
 end

resources :mr_consumers do
  collection do 
    get 'add_csv'
    post 'import'
  end
end 

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_filter :authenticate
  def index
    @users = User.find_all_by_is_admin(false)
  end

  private
   def authenticate
      deny_access unless signed_in?
    end

end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/index.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Import Users</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">

<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" ,:class =>"btn btn-primary"%>
<% end %>
<%= form_tag search_users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"  ,:class =>"btn btn-primary"%>
  </p>
<% end %>
<p>
<%= link_to "Show Readers", search_users_path(:name => "readers") ,:class =>"btn" %> |
<%= link_to "Show Vendors", search_users_path(:name => "vendors") ,:class =>"btn"%>
</p>
<p><%= link_to "Add Staff", add_staff_path,:class =>"btn" %></p>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-highlight">
<thead>
  <tr>
    <th>Sr. No.</th>
    <th>Full Name</th>
    <th>Username</th>
    <th colspan=2>Actions</th>
  </tr>
</thead>
<% @users.each.with_index(1) do |user,index| %>
  <tr>
    <td><%= index %></td>
    <td><%= user.first_name %> <%= user.last_name %></td>
    <td><%= user.username %></td>
    <td><%= link_to "Edit" , edit_user_path(user) , :class => "btn" %></td>
    <td><%= link_to "Delete" , user_path(user) ,method: :delete, data: { confirm: 'Are you sure ?' }, :class => "btn" %></td>
  </tr>
<% end %>
</table>


</div>  
</div>
</div>
</div>