config/routes.rb
require 'sidekiq/web'
Sndl::Application.routes.draw do
 

  resources :teams

  resources :meter_reader_statuses

  resources :meter_statuses

  resources :dtc_staffs,  :path => "clusters"

  resources :mobile_devises

  mount Sidekiq::Web, at: '/sidekiq'

  get "homes/index"

   root 'sessions#new'

   resources :users do
    collection { post :import }
    collection { get :search }
  end
 
  resources :sessions, :only => [:new,:create,:destroy,:edit]

  get 'dashboard' => 'users#dashboard', :as => 'user_root'

  get '/add_staff' =>'users#new'

  get '/signin' =>'sessions#new'

  get  '/users/:id/edit' => "users#edit" 

  post '/signout' =>'sessions#destroy'

  get '/readings/:id/toggled_status'  => "readings#toggled_status"

  get '/user/:id/dtc_staffs', :to => "users#dtc"

  get '/dtc_staff/:dtc', :to => "dtc_staffs#dtc"
 
  get '/consumer/:consno', :to => "consumers#consumer"

  post "/dtc_staffs/update_model", :to => "dtc_staffs#update_model" 

  get '/readings/submit', :to => "readings#submit"

  get '/mobileusers/:id/delete', :to => "mobileusers#destroy"

  get '/readings/consumer_status', :to => "readings#consumer_status"

   get '/readings/b30', :to => "readings#b30"

  get 'search'  => "teams#search"
 
  get 'search_vendor'  => "teams#search_vendor"
  
  get 'search_vendor_report'  => "readings#search_vendor_report"

  get 'search_vendor_summary'  => "readings#search_vendor_summary"
  
  get 'search_by_reader'  => "readings#search_by_reader"
  
  get  'search_by_date'  => "readings#search_by_date"

  get  'search_by_cluster'  => "readings#search_by_cluster"

  get  'search_by_date_summary'  => "readings#search_by_date_summary"

  get  'user_tracking'  => "readings#user_tracking"

  get  'user_tracking_report'  => "readings#user_tracking_report"

  get 'user_map' => 'readings#user_map'

 get 'search_all' => 'users#search_all'

  get 'readers_map' => 'readings#readers_map'
 
 resources :password_resets
 resources :staffs
 resources :readings do
  member do
    get 'show_image'
  end
  collection do
    get 'activity_report'
    get 'activity_summary_report'
  end
 end
resources :mobileusers

resources :consumers do
    collection do 
      get 'route_list'  => "consumers#route_list"
      get 'add_csv'
      get 'route'
      post 'import'
    end 
 end

resources :mr_consumers do
  collection do 
    get 'add_csv'
    post 'import'
  end
end 

end

app/models/mobileuser.rb
class Mobileuser < ActiveRecord::Base

attr_accessible :user_id,:imei

belongs_to :user

validates_uniqueness_of :imei,:user_id

end

app/controllers/mobileusers_controller.rb
class MobileusersController < ApplicationController
  before_filter :authenticate
 def index
    @mobileusers = Mobileuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mobileusers }
    end
  end

  # GET /banks/1
  # GET /banks/1.xml
  def show
    @mobileuser = Mobileuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mobileuser }
    end
  end

  # GET /banks/new
  # GET /banks/new.xml
  def new
    @mobileuser = Mobileuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mobileuser }
    end
  end

  # GET /banks/1/edit
  def edit
    @mobileuser = Mobileuser.find(params[:id])
  end

  # POST /banks
  # POST /banks.xml
  def create
    @mobileuser = Mobileuser.new(params[:mobileuser])

    respond_to do |format|
      if @mobileuser.save
        format.html { redirect_to(mobileusers_url, :notice => 'Mobile Assigned') }
        format.xml  { render :xml => @mobileuser, :status => :created, :location => @mobileuser }
      else
        format.html { render :action => "new" ,:notice => 'IMEI no already assign'}
        format.xml  { render :xml => @mobileuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /banks/1
  # PUT /banks/1.xml
  def update
    @mobileuser = Mobileuser.find(params[:id])

    respond_to do |format|
      if @mobileuser.update_attributes(params[:mobileuser])
        format.html { redirect_to(mobileusers_url, :notice => 'mobileuser was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mobileuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.xml
  def destroy
    @mobileuser = Mobileuser.find(params[:id])
    @mobileuser.destroy

    respond_to do |format|
      format.html { redirect_to(mobileusers_url) }
      format.xml  { head :ok }
    end
  end

  private
   
   def authenticate
      deny_access unless signed_in?
   end

 



end

app/helpers/mobileusers_helper.rb
module MobileusersHelper
end

app/views/mobileusers/_form.html.erb
  <% content_for :scripts do %>
   <%= javascript_include_tag  "jquery-1.5.2.min.js","jquery.validate.min","validation" %>
  <% end %>
<%= form_for(@mobileuser,:html => {:id => "mobileuser"}) do |f| %>
     <% if @mobileuser.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@mobileuser.errors.count, "error") %> prohibited this mobile_user from being saved:</h2>

                <ul>
                <% @mobileuser.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
<div>
    <%= f.label "Select Reader" %>
    <%= f.collection_select :user_id, User.find_all_by_role_id(2), :id, :first_name  ,:prompt => "Select Reader"%>
  </div><br />
 <div>
    <%= f.label "Select Imei" %>
    <%= f.collection_select :imei, MobileDevise.all(:order => "imei"), :imei, :imei  %>
  </div>
<br/>
<div class="actions">
	<%= f.submit "Save" ,:class => "btn btn-primary" %>
	
</div>
<% end %>

app/views/mobileusers/edit.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Edit Mobile User</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">

<%= render 'form' %>

</div>  
</div>
</div>
</div>

app/views/mobileusers/index.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Listing Mobile Users</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">


<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-highlight">
<thead>
  <tr>
    <th>Sr. No.</th>
    <th>Imei</th>
    <th>Name</th>
    <th colspan=2>Action</th>
  </tr>
</thead>
<% @mobileusers.each.with_index(1) do |mobileuser,index| %>
 <tr>
  <td><%= index %></td>
	<td><%= mobileuser.imei%></td>
   <td> <%= mobileuser.user.first_name rescue nil %></td>

  <td> 
   <%= link_to 'Edit', edit_mobileuser_path(mobileuser) ,:class=>"btn"%>
 </td>
  <td><a href="/mobileusers/<%= mobileuser.id %>/delete" onclick="if(confirm('Are you sure you want to delete this page?'))  return true;  else  return false;" class="btn" >Delete</a></td>
   </tr>   
<% end %>
</table>
<p><%= link_to "New Mobile User", new_mobileuser_path,:class =>"btn btn-secondary" %></p>
</div>  
</div>
</div>
</div>

app/views/mobileusers/new.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>New Mobile User</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">

<%= render 'form' %>

<p><%#= link_to "Back to List", mobileusers_path %></p>
</div>  
</div>
</div>
</div>

app/views/mobileusers/show.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Mobile User</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content"><p>
  <strong>IMEI</strong>
  <%= @mobileuser.imei %>
</p>

<p>
  <strong>user</strong>
 <%= @mobileuser.user.first_name rescue nil %>
</p>
</p>

<p>
  <%= link_to "Edit", edit_mobileuser_path(@mobileuser) %> |
  <%= link_to "Destroy", @mobileuser, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", mobileusers_path %>
</p>
</div>  
</div>
</div>
</div>