config/routes.rb
require 'sidekiq/web'
Sndl::Application.routes.draw do
 

  resources :teams

  resources :meter_reader_statuses

  resources :meter_statuses

  resources :dtc_staffs,  :path => "clusters"

  resources :mobile_devises

  mount Sidekiq::Web, at: '/sidekiq'

  get "homes/index"

   root 'sessions#new'

   resources :users do
    collection { post :import }
    collection { get :search }
  end
 
  resources :sessions, :only => [:new,:create,:destroy,:edit]

  get 'dashboard' => 'users#dashboard', :as => 'user_root'

  get '/add_staff' =>'users#new'

  get '/signin' =>'sessions#new'

  get  '/users/:id/edit' => "users#edit" 

  post '/signout' =>'sessions#destroy'

  get '/readings/:id/toggled_status'  => "readings#toggled_status"

  get '/user/:id/dtc_staffs', :to => "users#dtc"

  get '/dtc_staff/:dtc', :to => "dtc_staffs#dtc"
 
  get '/consumer/:consno', :to => "consumers#consumer"

  post "/dtc_staffs/update_model", :to => "dtc_staffs#update_model" 

  get '/readings/submit', :to => "readings#submit"

  get '/mobileusers/:id/delete', :to => "mobileusers#destroy"

  get '/readings/consumer_status', :to => "readings#consumer_status"

   get '/readings/b30', :to => "readings#b30"

  get 'search'  => "teams#search"
 
  get 'search_vendor'  => "teams#search_vendor"
  
  get 'search_vendor_report'  => "readings#search_vendor_report"

  get 'search_vendor_summary'  => "readings#search_vendor_summary"
  
  get 'search_by_reader'  => "readings#search_by_reader"
  
  get  'search_by_date'  => "readings#search_by_date"

  get  'search_by_cluster'  => "readings#search_by_cluster"

  get  'search_by_date_summary'  => "readings#search_by_date_summary"

  get  'user_tracking'  => "readings#user_tracking"

  get  'user_tracking_report'  => "readings#user_tracking_report"

  get 'user_map' => 'readings#user_map'

 get 'search_all' => 'users#search_all'

  get 'readers_map' => 'readings#readers_map'
 
 resources :password_resets
 resources :staffs
 resources :readings do
  member do
    get 'show_image'
  end
  collection do
    get 'activity_report'
    get 'activity_summary_report'
  end
 end
resources :mobileusers

resources :consumers do
    collection do 
      get 'route_list'  => "consumers#route_list"
      get 'add_csv'
      get 'route'
      post 'import'
    end 
 end

resources :mr_consumers do
  collection do 
    get 'add_csv'
    post 'import'
  end
end 

end

app/views/shared/_date_search.html.erb
<%= form_tag search_by_date_path, :method => 'get' do %>

<table>
  <tr>
    <td>Date From :</td>
    <td><input type="text_field" class="date_time" name="start_date" id="start_date"></td>
   </tr>
  <tr>
    <td>Date To :</td> 
    <td><input type="text_field" class="date_time1" name="end_date" id="end_date"></td>
  </tr>
</table>

<% if params[:action] == 'index' %>
 <%= hidden_field_tag :reading_index , "reading_index"%>
<% elsif params[:action] == 'consumer_status' %>
 <%=  hidden_field_tag :consumer_status ,params["consumer_status"] %>
<% end %>

<br/>
<%= submit_tag "Search By Date" ,:class =>"btn btn-primary"%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(object.errors.count, "error") %>
prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

    	<div class="container">

    		<div class="row">
          
    			<div id="footer-copyright" class="span6">
    				&copy; 2013-14 Kunal Infotech Pvt. Ltd. Meter Reading
    			</div> <!-- /span6 -->



    		</div> <!-- /row -->

    	</div> <!-- /container -->

    </div>

app/views/shared/_menu.html.erb
    <div class="subnavbar">

    	<div class="subnavbar-inner">

    		<div class="container">

    			<a class="btn-subnavbar collapsed" data-toggle="collapse" data-target=".subnav-collapse">
    				<i class="icon-reorder"></i>
    			</a>

    			<div class="subnav-collapse collapse">
    				<ul class="mainnav">

    					<li class="dropdown">
    						<a href="<%= readings_path %>">
    							<i><img src="/assets/reading.png" alt=""></i>
    							<span>Readings</span>
    						</a>	    				
    					</li>
                            <li class="dropdown">                   
                            <a href="<%= staffs_path %>">
                                <i><img src="/assets/staff.png" alt=""></i>
                                <span>Add Staff</span>
                            </a>    
                        </li>

                 <!--        <li class="dropdown">                   
                            <a href="<%#= teams_path %>">
                                <i><img src="/assets/team.png" alt=""></i>
                                <span>Team</span>
                            </a>    
                        </li> -->

    					<li class="dropdown">					
    						<a href="<%= mobile_devises_path %>" >
    							<i><img src="/assets/mobile.png" alt=""></i>
    							<span>Add Mobile</span>

    						</a>	    

    					</li>
                         <li class="dropdown">                   
                            <a href="<%= mobileusers_path %>">
                                <i><img src="/assets/mobile.png" alt=""></i>
                                <span>Assign Mobile </br>To Reader</span>
                            </a>    
                        </li>

                        <li class="dropdown">                   
                            <a href="<%= add_csv_mr_consumers_path %>">
                                <i><img src="/assets/excel2.png" alt=""></i>
                                <span>Upload</br>Consumers</span>
                            </a>    
                        </li>


                        <li class="dropdown">                   
                            <a href="<%= dtc_staffs_path %>">
                                <i><img src="/assets/distribution.png" alt=""></i>
                                <span>Associate Route </br>To Staff</span>
                            </a>    
                        </li>


                        <li class="dropdown">                   
                            <a href="<%= meter_statuses_path %>">
                                <i><img src="/assets/meter_status.png" alt=""></i>
                                <span>Meter Status</span>
                            </a>    
                        </li>

                        <li class="dropdown">                   
                            <a href="<%= meter_reader_statuses_path %>">
                                <i><img src="/assets/meter_readers_tatus.png" alt=""></i>
                                <span>Meter Reader</br> Status</span>
                            </a>    
                        </li>

                        
    					<li class="dropdown">					
    						<a href="<%= activity_report_readings_path %>" >
    							<i><img src="/assets/report.png" alt=""></i>
    							<span>MIS/Report</span>

    						</a>	    


    					</li>
                            <li class="dropdown">                   
                            <a href="<%= user_tracking_path %>" >
                                <i><img src="/assets/report.png" alt=""></i>
                                <span>Reader Report</span>

                            </a>        


                        </li>
          
    				
    				</ul>
    			</div> <!-- /.subnav-collapse -->

    		</div> <!-- /container -->

    	</div> <!-- /subnavbar-inner -->

    </div>

app/views/shared/_readingss.html.erb
	 <td><%= reading.consumer_no rescue nil%>&nbsp;</td>
         <td><%= reading.user.first_name rescue nil%>&nbsp;</td>
         <td><%= reading.remark  rescue nil %>
        </td>
        <td><%= reading.old_meter_no rescue nil %></td>
        <td><%= reading.new_meter_no rescue nil %></td>
        <td><%= reading.meter_reading.to_i  rescue nil%>&nbsp;</td>
        <td><%= reading.sub_cluster rescue nil%>&nbsp;</td>
        <td><%= reading.meter_status rescue nil%>&nbsp;</td>
        <td><%= reading.meter_reader_status rescue nil%>&nbsp;</td>
        <td><%= reading.created_at.strftime("%T %a %b %e %Y ")   %></td>
        <td><%= image_tag reading.image.url ,:class => "img1" rescue nil %></td>
        <td> <%= link_to 'Show', reading,:class => "btn btn-primary" %></td>
         <td><%= link_to "Reject", reading , method: :delete, data: { confirm: 'Are you sure, you want to reject reading?' }, :class => "btn btn-primary" %></td>