config/routes.rb
require 'sidekiq/web'
Sndl::Application.routes.draw do
 

  resources :teams

  resources :meter_reader_statuses

  resources :meter_statuses

  resources :dtc_staffs,  :path => "clusters"

  resources :mobile_devises

  mount Sidekiq::Web, at: '/sidekiq'

  get "homes/index"

   root 'sessions#new'

   resources :users do
    collection { post :import }
    collection { get :search }
  end
 
  resources :sessions, :only => [:new,:create,:destroy,:edit]

  get 'dashboard' => 'users#dashboard', :as => 'user_root'

  get '/add_staff' =>'users#new'

  get '/signin' =>'sessions#new'

  get  '/users/:id/edit' => "users#edit" 

  post '/signout' =>'sessions#destroy'

  get '/readings/:id/toggled_status'  => "readings#toggled_status"

  get '/user/:id/dtc_staffs', :to => "users#dtc"

  get '/dtc_staff/:dtc', :to => "dtc_staffs#dtc"
 
  get '/consumer/:consno', :to => "consumers#consumer"

  post "/dtc_staffs/update_model", :to => "dtc_staffs#update_model" 

  get '/readings/submit', :to => "readings#submit"

  get '/mobileusers/:id/delete', :to => "mobileusers#destroy"

  get '/readings/consumer_status', :to => "readings#consumer_status"

   get '/readings/b30', :to => "readings#b30"

  get 'search'  => "teams#search"
 
  get 'search_vendor'  => "teams#search_vendor"
  
  get 'search_vendor_report'  => "readings#search_vendor_report"

  get 'search_vendor_summary'  => "readings#search_vendor_summary"
  
  get 'search_by_reader'  => "readings#search_by_reader"
  
  get  'search_by_date'  => "readings#search_by_date"

  get  'search_by_cluster'  => "readings#search_by_cluster"

  get  'search_by_date_summary'  => "readings#search_by_date_summary"

  get  'user_tracking'  => "readings#user_tracking"

  get  'user_tracking_report'  => "readings#user_tracking_report"

  get 'user_map' => 'readings#user_map'

 get 'search_all' => 'users#search_all'

  get 'readers_map' => 'readings#readers_map'
 
 resources :password_resets
 resources :staffs
 resources :readings do
  member do
    get 'show_image'
  end
  collection do
    get 'activity_report'
    get 'activity_summary_report'
  end
 end
resources :mobileusers

resources :consumers do
    collection do 
      get 'route_list'  => "consumers#route_list"
      get 'add_csv'
      get 'route'
      post 'import'
    end 
 end

resources :mr_consumers do
  collection do 
    get 'add_csv'
    post 'import'
  end
end 

end

app/controllers/meter_reader_statuses_controller.rb
class MeterReaderStatusesController < ApplicationController
  before_action :set_meter_reader_status, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate 

   


  # GET /meter_reader_statuses
  # GET /meter_reader_statuses.json
  def index
    @meter_reader_statuses = MeterReaderStatus.all
  end

  # GET /meter_reader_statuses/1
  # GET /meter_reader_statuses/1.json
  def show
  end

  # GET /meter_reader_statuses/new
  def new
    @meter_reader_status = MeterReaderStatus.new
  end

  # GET /meter_reader_statuses/1/edit
  def edit
  end

  # POST /meter_reader_statuses
  # POST /meter_reader_statuses.json
  def create
    @meter_reader_status = MeterReaderStatus.new(meter_reader_status_params)

    respond_to do |format|
      if @meter_reader_status.save
        format.html { redirect_to meter_reader_statuses_url, notice: 'Meter reader status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meter_reader_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @meter_reader_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meter_reader_statuses/1
  # PATCH/PUT /meter_reader_statuses/1.json
  def update
    respond_to do |format|
      if @meter_reader_status.update(meter_reader_status_params)
        format.html { redirect_to meter_reader_statuses_url, notice: 'Meter reader status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meter_reader_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meter_reader_statuses/1
  # DELETE /meter_reader_statuses/1.json
  def destroy
    @meter_reader_status.destroy
    respond_to do |format|
      format.html { redirect_to meter_reader_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter_reader_status
      @meter_reader_status = MeterReaderStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meter_reader_status_params
      params.require(:meter_reader_status).permit(:description,:meter_statuses_id)
    end

     
  def authenticate
    deny_access unless signed_in?
  end
end

app/helpers/meter_reader_statuses_helper.rb
module MeterReaderStatusesHelper
end

app/views/meter_reader_statuses/_form.html.erb
<%= form_for(@meter_reader_status) do |f| %>
  <% if @meter_reader_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter_reader_status.errors.count, "error") %> prohibited this meter_reader_status from being saved:</h2>

      <ul>
      <% @meter_reader_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
<!--  <div>
   <%#= f.label :meter_status_id %><br>
   <%#= f.collection_select :meter_status_id, MeterStatus.all(:order => "id"), :id, :billing_meter_status %>
  </div> --></br>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/meter_reader_statuses/edit.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Editing Meter Reader Status</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">


<%= render 'form' %>

<%#= link_to 'Show', @meter_reader_status %> 
<%#= link_to 'Back', meter_reader_statuses_path %>
</div>  
</div>
</div>
</div>

app/views/meter_reader_statuses/index.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Listing Meter Reader Statuses</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">


<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-highlight">
  <thead>
    <tr>
      <th>Sr. No.</th>
      <th>Description</th>
      <th colspan = 2>Action</th>
      </tr>
  </thead>

  <tbody>
    <% @meter_reader_statuses.each.with_index(1) do |meter_reader_status,index| %>
      <tr>
        <td><%= index %></td>
        <td><%= meter_reader_status.description %></td>
        <td><%= link_to 'Edit', edit_meter_reader_status_path(meter_reader_status) ,:class=>"btn" %></td>
        <td><%= link_to 'Delete', meter_reader_status, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meter reader status', new_meter_reader_status_path,:class =>"btn btn-secondary" %>
</div>  
</div>
</div>
</div>

app/views/meter_reader_statuses/new.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>New Meter Reader Status</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">


<%= render 'form' %>

<%#= link_to 'Back', meter_reader_statuses_path %>
</div>  
</div>
</div>
</div>

app/views/meter_reader_statuses/show.html.erb
  <div class="row">
        
    <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Meter Reader Status</h3>
          </div> <!-- /widget-header -->
        
             <div class="widget-content">
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @meter_reader_status.description %>
</p>


</div>  
</div>
</div>
</div>